version: '3.1'

services:
  app:
    build: .
    container_name: macal-app
    env_file:
      - .env
    ports:
      - "${PORT}:3001"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - macal-network

  postgres:
    image: postgres
    container_name: macal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: macal
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - macal-network

volumes:
  postgres-data:

networks:
  macal-network: