version: '3.1'

services:
  mongo:
    image: mongo
    container_name: macal-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  postgres:
    image: postgres
    container_name: macal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: macal
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

